import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'

import { allPosts } from '../.contentlayer/generated/index.mjs'

// TODO setup watching for file name changes

const allPostSlugs = allPosts
	.filter(post => !post.draft)
	.map(post => post.slug)

const out = `
// THIS FILE IS AUTOGENERATED. DO NOT EDIT

const allPostSlugs = ${JSON.stringify(allPostSlugs)}
export default allPostSlugs
`

const cacheFolder = './.cache'

if (!existsSync(cacheFolder)) {
	await mkdir(cacheFolder)
}

await writeFile(`${cacheFolder}/allPostSlugs.mjs`, out).catch(console.error)

console.log('✅ Cached Post Slugs')